### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by vitovt** [wther/redmine-gamification#1]
Hi,

this looks like a great job! Really awesome. Could you please help install this plugin ? Or can you write some installation instructions, on how to get started.

Thanks a lot for your help!

**Comment by vitovt** [comment]
I've cloned it to my public directory of redmine.
Then changed url and credentials which are hardcoded in 
public/redmine-gamification/python/redminereader.py

Then I've tried to run:
`python public/redmine-gamification/python/runner.py --url http://my-url.com/ --user MyUser --password MyPassword --project marketing-advertising --days=25 app/data/data.json`

and I see:

``` http://my-site.com/projects/marketing-advertising.json
Traceback (most recent call last):
  File "public/redmine-gamification/python/runner.py", line 24, in <module>
    verify=False)
  File "/var/www/mysite/public/redmine-gamification/python/redminereader.py", line 41, in __init__
    self.project = self.redmine.project.get(project_name)
  File "/var/www/mysite/public/redmine-gamification/python/redmine/managers.py", line 127, in get
    return self.resource_class(self, self.retrieve()[0])
  File "/var/www/mysite/public/redmine-gamification/python/redmine/managers.py", line 60, in retrieve
    response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
  File "/var/www/mysite/public/redmine-gamification/python/redmine/__init__.py", line 133, in request
    raise AuthError
redmine.exceptions.AuthError: Invalid authentication details
```

**Comment by wther** [comment]
Great catch with the hard coded credentials, it's kind of embarrassing really. Forced pushed the fix, please pull from the repo again, the command line arguments are working now. 

With the exception you see my best bet is that either the username/password is incorrect or some Redmine setting prevents you to access the HTTP API of Redmine.

Created a wiki page here on how to debug the problem: https://github.com/wther/redmine-gamification/wiki.

I'm pretty sure that the current functionality will not fit your needs entirely. Feel free to create issues/feature requests.

**Comment by wther** [comment]
Closing this for lack of further interest.
